import sys.FileSystem;
import sys.io.File;

using StringTools;

private final OUT_FILE = "main.js";

private function error(msg, code = 1) {
	Sys.stderr().writeString(msg + "\n");
	Sys.exit(code);
}

private function runHaxe(args:Array<String>):sys.io.Process {
	final process = new sys.io.Process("haxe", args);
	final exitCode = process.exitCode();
	if (exitCode != 0)
		throw "Unable to compile: " + process.stderr.readAll().toString() + "\n";
	return process;
}

function main() {
	// default
	runHaxe(["Tools", "--js", OUT_FILE]);
	if (!File.getContent(OUT_FILE).startsWith("// Generated by Haxe"))
		error("Default source header is missing");

	// dash flags

	// empty
	runHaxe(["Tools", "--js", OUT_FILE, "-D", "source-header="]);
	if (File.getContent(OUT_FILE).startsWith("//"))
		error("Source header is still present");

	// custom
	runHaxe(["Tools", "--js", OUT_FILE, "-D", "source-header=custom"]);
	if (!File.getContent(OUT_FILE).startsWith("// custom"))
		error("Custom source header is missing");

	// underscore flags

	// empty
	runHaxe(["Tools", "--js", OUT_FILE, "-D", "source_header="]);
	if (File.getContent(OUT_FILE).startsWith("//"))
		error("Source header is still present with `-D source_header`");

	// custom
	runHaxe(["Tools", "--js", OUT_FILE, "-D", "source_header=custom"]);
	if (!File.getContent(OUT_FILE).startsWith("// custom"))
		error("Custom source header is missing");

	FileSystem.deleteFile(OUT_FILE);
}
