import sys.FileSystem;
import sys.io.File;

using StringTools;

private final OUT_FILE = "main.js";

function main() {
	// default
	Tools.runHaxe(["--main", "Main", "--js", OUT_FILE]);
	if (!File.getContent(OUT_FILE).startsWith("// Generated by Haxe"))
		Tools.error("Default source header is missing");

	// dash flags

	// empty
	Tools.runHaxe(["--main", "Main", "--js", OUT_FILE, "-D", "source-header="]);
	if (File.getContent(OUT_FILE).startsWith("//"))
		Tools.error("Source header is still present");

	// custom
	Tools.runHaxe(["--main", "Main", "--js", OUT_FILE, "-D", "source-header=custom"]);
	if (!File.getContent(OUT_FILE).startsWith("// custom"))
		Tools.error("Custom source header is missing");

	// underscore flags

	// empty
	Tools.runHaxe(["--main", "Main", "--js", OUT_FILE, "-D", "source_header="]);
	if (File.getContent(OUT_FILE).startsWith("//"))
		Tools.error("Source header is still present with `-D source_header`");

	// custom
	Tools.runHaxe(["--main", "Main", "--js", OUT_FILE, "-D", "source_header=custom"]);
	if (!File.getContent(OUT_FILE).startsWith("// custom"))
		Tools.error("Custom source header is missing");

	FileSystem.deleteFile(OUT_FILE);
}
